mongodb:
max:
  pool:
    size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
  name: 4sell
  retry:
    attempts: 10
    delay: 10000
  data:
    mongodb:
      database:  4sell
      authentication-database: admin
      host: mongodb
      port: 27017
